const WORD_PAIRS = [
  ["Coca-Cola", "Pepsi"],
  ["Pizza", "Tarte flambée"],
  ["Chien", "Loup"],
  ["Chat", "Tigre"],
  ["Soleil", "Lune"],
  ["Plage", "Piscine"],
  ["Voiture", "Moto"],
  ["Bière", "Cidre"],
  ["Chocolat noir", "Chocolat au lait"],
  ["Facebook", "Instagram"],
  ["iPhone", "Android"],
  ["Netflix", "Disney+"],
  ["Paris", "Lyon"],
  ["Foot", "Rugby"],
  ["Tennis", "Badminton"],
  ["Guitare", "Basse"],
  ["Café", "Thé"],
  ["Pain", "Baguette"],
  ["Fromage", "Beurre"],
  ["Vin rouge", "Vin rosé"],
  ["Cinéma", "Théâtre"],
  ["Avion", "Hélicoptère"],
  ["Mer", "Lac"],
  ["Montagne", "Colline"],
  ["Hiver", "Automne"],
  ["Noel", "Halloween"],
  ["Médecin", "Infirmier"],
  ["Pompier", "Policier"],
  ["Professeur", "Directeur"],
  ["Boulanger", "Pâtissier"],
  ["Requin", "Dauphin"],
  ["Lion", "Panthère"],
  ["Éléphant", "Rhinocéros"],
  ["Aigle", "Vautour"],
  ["Fraise", "Framboise"],
  ["Pomme", "Poire"],
  ["Orange", "Mandarine"],
  ["Banane", "Plantain"],
  ["Sushi", "Maki"],
  ["Burger", "Sandwich"],
  ["Piscine", "Jacuzzi"],
  ["Hôtel", "Auberge"],
  ["Camping", "Glamping"],
  ["Vélo", "Trottinette"],
  ["Train", "Métro"],
  ["Bateau", "Pédalo"],
  ["Natation", "Plongée"],
  ["Yoga", "Pilates"],
  ["Boxe", "Karaté"],
  ["Escalade", "Spéléologie"],
  ["Mariage", "Fiançailles"],
  ["Anniversaire", "Fête"],
  ["Diplôme", "Concours"],
  ["Vacances", "Week-end"],
  ["Bibliothèque", "Librairie"],
  ["Musée", "Galerie"],
  ["Parc", "Jardin"],
  ["Supermarché", "Épicerie"],
  ["Pharmacie", "Clinique"],
  ["Banque", "Distributeur"],
  ["Whisky", "Rhum"],
  ["Champagne", "Prosecco"],
  ["Vodka", "Gin"],
  ["Jeans", "Pantalon"],
  ["T-shirt", "Polo"],
  ["Baskets", "Running"],
  ["Casquette", "Bonnet"],
  ["Manteau", "Imperméable"],
  ["Robe", "Jupe"],
  ["Sac à dos", "Sac de sport"],
  ["Montre", "Bracelet connecté"],
  ["Ordinateur", "Tablette"],
  ["Télévision", "Projecteur"],
  ["Imprimante", "Scanner"],
  ["Clavier", "Souris"],
  ["Micro-ondes", "Four"],
  ["Frigo", "Congélateur"],
  ["Lave-vaisselle", "Lave-linge"],
  ["Canapé", "Fauteuil"],
  ["Lit", "Matelas"],
  ["Lampe", "Bougie"],
  ["Tableau", "Affiche"],
  ["Tapis", "Parquet"],
  ["Rideau", "Store"],
  ["Roses", "Tulipes"],
  ["Marguerites", "Tournesols"],
  ["Cactus", "Bambou"],
  ["Chêne", "Hêtre"],
  ["Sapin", "Pin"],
  ["Harry Potter", "Seigneur des Anneaux"],
  ["Star Wars", "Star Trek"],
  ["Marvel", "DC Comics"],
  ["James Bond", "Jason Bourne"],
  ["Titanic", "Naufrage"],
  ["Fantôme", "Zombie"],
  ["Vampire", "Loup-garou"],
  ["Dragon", "Dinosaure"],
  ["Licorne", "Pégase"],
  ["Pirate", "Corsaire"],
];

module.exports = WORD_PAIRS;
