// Liste de paires de mots pour le jeu Undercover
// Format: { civil: "mot connu de tous", undercover: "mot proche mais différent" }

const WORD_PAIRS = [
  { civil: "Coca-Cola", undercover: "Pepsi" },
  { civil: "Pizza", undercover: "Tarte flambée" },
  { civil: "Chien", undercover: "Loup" },
  { civil: "Chat", undercover: "Tigre" },
  { civil: "Soleil", undercover: "Lune" },
  { civil: "Plage", undercover: "Piscine" },
  { civil: "Voiture", undercover: "Moto" },
  { civil: "Bière", undercover: "Cidre" },
  { civil: "Chocolat noir", undercover: "Chocolat au lait" },
  { civil: "Facebook", undercover: "Instagram" },
  { civil: "iPhone", undercover: "Android" },
  { civil: "Netflix", undercover: "Disney+" },
  { civil: "Paris", undercover: "Lyon" },
  { civil: "Foot", undercover: "Rugby" },
  { civil: "Tennis", undercover: "Badminton" },
  { civil: "Guitare", undercover: "Basse" },
  { civil: "Café", undercover: "Thé" },
  { civil: "Pain", undercover: "Baguette" },
  { civil: "Fromage", undercover: "Beurre" },
  { civil: "Vin rouge", undercover: "Vin rosé" },
  { civil: "Cinéma", undercover: "Théâtre" },
  { civil: "Avion", undercover: "Hélicoptère" },
  { civil: "Mer", undercover: "Lac" },
  { civil: "Montagne", undercover: "Colline" },
  { civil: "Hiver", undercover: "Automne" },
  { civil: "Noel", undercover: "Halloween" },
  { civil: "Médecin", undercover: "Infirmier" },
  { civil: "Pompier", undercover: "Policier" },
  { civil: "Professeur", undercover: "Directeur" },
  { civil: "Boulanger", undercover: "Pâtissier" },
  { civil: "Requin", undercover: "Dauphin" },
  { civil: "Lion", undercover: "Panthère" },
  { civil: "Éléphant", undercover: "Rhinocéros" },
  { civil: "Aigle", undercover: "Vautour" },
  { civil: "Fraise", undercover: "Framboise" },
  { civil: "Pomme", undercover: "Poire" },
  { civil: "Orange", undercover: "Mandarine" },
  { civil: "Banane", undercover: "Plantain" },
  { civil: "Sushi", undercover: "Maki" },
  { civil: "Burger", undercover: "Sandwich" },
  { civil: "Piscine", undercover: "Jacuzzi" },
  { civil: "Hôtel", undercover: "Auberge" },
  { civil: "Camping", undercover: "Glamping" },
  { civil: "Vélo", undercover: "Trottinette" },
  { civil: "Train", undercover: "Métro" },
  { civil: "Bateau", undercover: "Pédalo" },
  { civil: "Natation", undercover: "Plongée" },
  { civil: "Yoga", undercover: "Pilates" },
  { civil: "Boxe", undercover: "Karaté" },
  { civil: "Escalade", undercover: "Spéléologie" },
  { civil: "Mariage", undercover: "Fiançailles" },
  { civil: "Anniversaire", undercover: "Fête" },
  { civil: "Diplôme", undercover: "Concours" },
  { civil: "Vacances", undercover: "Week-end" },
  { civil: "Bibliothèque", undercover: "Librairie" },
  { civil: "Musée", undercover: "Galerie" },
  { civil: "Parc", undercover: "Jardin" },
  { civil: "Supermarché", undercover: "Épicerie" },
  { civil: "Pharmacie", undercover: "Clinique" },
  { civil: "Banque", undercover: "Distributeur" },
  { civil: "Whisky", undercover: "Rhum" },
  { civil: "Champagne", undercover: "Prosecco" },
  { civil: "Vodka", undercover: "Gin" },
  { civil: "Jeans", undercover: "Pantalon" },
  { civil: "T-shirt", undercover: "Polo" },
  { civil: "Baskets", undercover: "Running" },
  { civil: "Casquette", undercover: "Bonnet" },
  { civil: "Manteau", undercover: "Imperméable" },
  { civil: "Robe", undercover: "Jupe" },
  { civil: "Sac à dos", undercover: "Sac de sport" },
  { civil: "Montre", undercover: "Bracelet connecté" },
  { civil: "Ordinateur", undercover: "Tablette" },
  { civil: "Télévision", undercover: "Projecteur" },
  { civil: "Imprimante", undercover: "Scanner" },
  { civil: "Clavier", undercover: "Souris" },
  { civil: "Micro-ondes", undercover: "Four" },
  { civil: "Frigo", undercover: "Congélateur" },
  { civil: "Lave-vaisselle", undercover: "Lave-linge" },
  { civil: "Canapé", undercover: "Fauteuil" },
  { civil: "Lit", undercover: "Matelas" },
  { civil: "Lampe", undercover: "Bougie" },
  { civil: "Tableau", undercover: "Affiche" },
  { civil: "Tapis", undercover: "Parquet" },
  { civil: "Rideau", undercover: "Store" },
  { civil: "Roses", undercover: "Tulipes" },
  { civil: "Marguerites", undercover: "Tournesols" },
  { civil: "Cactus", undercover: "Bambou" },
  { civil: "Chêne", undercover: "Hêtre" },
  { civil: "Sapin", undercover: "Pin" },
  { civil: "Harry Potter", undercover: "Seigneur des Anneaux" },
  { civil: "Star Wars", undercover: "Star Trek" },
  { civil: "Marvel", undercover: "DC Comics" },
  { civil: "James Bond", undercover: "Jason Bourne" },
  { civil: "Titanic", undercover: "Naufrage" },
  { civil: "Fantôme", undercover: "Zombie" },
  { civil: "Vampire", undercover: "Loup-garou" },
  { civil: "Dragon", undercover: "Dinosaure" },
  { civil: "Licorne", undercover: "Pégase" },
  { civil: "Pirate", undercover: "Corsaire" },
];

module.exports = WORD_PAIRS;
